In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("WeatherPy_vacation.csv")
vacation_df.head()


City_ID             City Country  Max Temp Current Description      Lat  \
0        0  Puerto Colombia      CO     80.69     overcast clouds  10.9878   
1        2           Atuona      PF     77.90           clear sky  -9.8000   
2        3             Aksu      CN     82.87       broken clouds  41.1231   
3        8         Hukuntsi      BW     76.23    scattered clouds -24.0000   
4       11          Kavieng      PG     82.00     overcast clouds  -2.5744   

        Lng            Hotel Name  
0  -74.9547    Hotel El Emigrante  
1 -139.0333           Villa Enata  
2   80.2644  Pudong Holiday Hotel  
3   21.7500        Entabeni Hotel  
4  150.7967   Nusa Island Retreat

In [22]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [23]:
# 4a. Add a marker layer for each city to the map.
locations = vacation_df[["Lat", "Lng"]]
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=vacation_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [24]:
#From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[(vacation_df['City']=='Alexandria')
                                & (vacation_df['Hotel Name']=='Royal Crown Hotel')]
vacation_end = vacation_df.loc[(vacation_df['City']=='Alexandria')
                              & (vacation_df['Hotel Name']=='Royal Crown Hotel')]
vacation_stop1 = vacation_df.loc[(vacation_df['City']=='Saint-Georges')
                              & (vacation_df['Hotel Name']=='Radisson Grenada Beach Resort')]
vacation_stop2 = vacation_df.loc[(vacation_df['City']=='Tura')
                                & (vacation_df['Hotel Name']=='Hotel RIKMAN Continental')] 
vacation_stop3 = vacation_df.loc[(vacation_df['City']=='Hithadhoo')
                                & (vacation_df['Hotel Name']=='Scoop Guest House')] 

In [25]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = pd.DataFrame(vacation_start[["Lat", "Lng"]]).to_numpy()
end = pd.DataFrame(vacation_end[["Lat", "Lng"]]).to_numpy()
stop1 = pd.DataFrame(vacation_stop1[["Lat", "Lng"]]).to_numpy()
stop2 = pd.DataFrame(vacation_stop2[["Lat", "Lng"]]).to_numpy()
stop3 = pd.DataFrame(vacation_stop3[["Lat", "Lng"]]).to_numpy()
start, stop1, stop2, stop3

(array([[31.2156, 29.9553]]),
 array([[ 12.0564, -61.7485]]),
 array([[25.5198, 90.2201]]),
 array([[-0.6   , 73.0833]]))

In [26]:
# add the latitude/longitude
start=(31.2156, 29.9553)
end=(31.2156, 29.9553)
stop1=(12.0564, -61.7485)
stop2=(25.5198, 90.2201)
stop3=(-0.6, 73.0833)

In [27]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
fig = gmaps.figure()
itinerary_trip_plan = gmaps.directions_layer(start,end, 
                                             waypoints=[stop1,stop2,stop3],
                                             travel_mode="DRIVING")
fig.add_layer(itinerary_trip_plan)
fig

Figure(layout=FigureLayout(height='420px'))

In [28]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3],ignore_index=True)
itinerary_df

City_ID           City Country  Max Temp Current Description      Lat  \
0      197     Alexandria      EG     75.16    scattered clouds  31.2156   
1      498  Saint-Georges      GD     82.08    scattered clouds  12.0564   
2      624           Tura      IN     76.24       broken clouds  25.5198   
3       97      Hithadhoo      MV     83.50       broken clouds  -0.6000   

       Lng                     Hotel Name  
0  29.9553              Royal Crown Hotel  
1 -61.7485  Radisson Grenada Beach Resort  
2  90.2201       Hotel RIKMAN Continental  
3  73.0833              Scoop Guest House

In [37]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
itinerary_locations = itinerary_df[["Lat", "Lng"]]

In [39]:
# 11a. Add a marker layer for each city to the map.
itinerary_locations = itinerary_df[["Lat", "Lng"]]
fig = gmaps.figure(center=(31.0, 29.0), zoom_level=5)
marker_layer = gmaps.marker_layer(itinerary_locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

In [40]:
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))